/**
 * Complete spelling word bank, grades 4 through 9.
 * Each entry carries everything the app needs: the word, its grade level,
 * a kid-friendly definition, an example sentence, syllable breaks, and
 * an optional pronunciation override for the speech synthesizer.
 */

export interface BankWord {
  word: string;
  grade: number;
  definition: string;
  example: string;
  syllables: string;
  pronunciationOverride?: string;
}

export const WORD_BANK: BankWord[] = [
  // ──────────────────────────────────────────────
  // GRADE 4
  // ──────────────────────────────────────────────
  { word: "beautiful", grade: 4, definition: "very pleasing to look at or experience", example: "The sunset over the lake was beautiful.", syllables: "beau-ti-ful" },
  { word: "because", grade: 4, definition: "for the reason that", example: "We stayed inside because it was raining.", syllables: "be-cause" },
  { word: "believe", grade: 4, definition: "to feel sure that something is true", example: "I believe we can win the game.", syllables: "be-lieve" },
  { word: "between", grade: 4, definition: "in the space separating two things", example: "The ball rolled between the two chairs.", syllables: "be-tween" },
  { word: "calendar", grade: 4, definition: "a chart showing the days, weeks, and months of a year", example: "Mark your birthday on the calendar.", syllables: "cal-en-dar" },
  { word: "caught", grade: 4, definition: "grabbed or captured something", example: "She caught the ball with one hand.", syllables: "caught" },
  { word: "chocolate", grade: 4, definition: "a sweet brown food made from cacao beans", example: "He ate a piece of chocolate after lunch.", syllables: "choc-o-late" },
  { word: "climate", grade: 4, definition: "the usual weather conditions in a place", example: "The climate near the ocean is mild.", syllables: "cli-mate" },
  { word: "complete", grade: 4, definition: "having all parts; to finish something", example: "She will complete her homework before dinner.", syllables: "com-plete" },
  { word: "courage", grade: 4, definition: "bravery when facing something scary", example: "It took courage to stand up and speak.", syllables: "cour-age" },
  { word: "daughter", grade: 4, definition: "a female child", example: "Their daughter plays soccer every Saturday.", syllables: "daugh-ter" },
  { word: "describe", grade: 4, definition: "to tell what something is like using words", example: "Can you describe what you saw?", syllables: "de-scribe" },
  { word: "different", grade: 4, definition: "not the same as another", example: "Each snowflake is different from the rest.", syllables: "dif-fer-ent" },
  { word: "difficult", grade: 4, definition: "hard to do or understand", example: "The math test was more difficult than I expected.", syllables: "dif-fi-cult" },
  { word: "disappear", grade: 4, definition: "to go out of sight", example: "The rabbit seemed to disappear into the hat.", syllables: "dis-ap-pear" },
  { word: "discover", grade: 4, definition: "to find or learn something for the first time", example: "Scientists discover new species every year.", syllables: "dis-cov-er" },
  { word: "distance", grade: 4, definition: "the amount of space between two places", example: "The distance from home to school is two miles.", syllables: "dis-tance" },
  { word: "energy", grade: 4, definition: "the power to do work or be active", example: "The sun provides energy to the whole planet.", syllables: "en-er-gy" },
  { word: "enough", grade: 4, definition: "as much as is needed", example: "Do we have enough snacks for everyone?", syllables: "e-nough" },
  { word: "escape", grade: 4, definition: "to get away from a place or danger", example: "The cat tried to escape through the open door.", syllables: "es-cape" },
  { word: "exercise", grade: 4, definition: "physical activity to stay healthy", example: "Walking is a good form of exercise.", syllables: "ex-er-cise" },
  { word: "experiment", grade: 4, definition: "a test done to learn something new", example: "The science experiment took three days.", syllables: "ex-per-i-ment" },
  { word: "explain", grade: 4, definition: "to make something clear so someone understands", example: "The teacher will explain the directions again.", syllables: "ex-plain" },
  { word: "favorite", grade: 4, definition: "the one you like the most", example: "Pizza is my favorite food.", syllables: "fa-vor-ite" },
  { word: "finally", grade: 4, definition: "at last; after a long time", example: "We finally arrived at the campground.", syllables: "fi-nal-ly" },
  { word: "forward", grade: 4, definition: "toward the front; ahead", example: "Take two steps forward.", syllables: "for-ward" },
  { word: "grocery", grade: 4, definition: "a store that sells food and household items", example: "Mom went to the grocery store for milk.", syllables: "gro-cer-y" },
  { word: "guard", grade: 4, definition: "to watch over and protect", example: "The dog will guard the house while we are gone.", syllables: "guard" },
  { word: "height", grade: 4, definition: "how tall something is", example: "The height of the building is fifty feet.", syllables: "height" },
  { word: "island", grade: 4, definition: "a piece of land surrounded by water", example: "We took a boat to the small island.", syllables: "is-land" },
  { word: "knowledge", grade: 4, definition: "what you know from learning or experience", example: "Reading builds your knowledge.", syllables: "knowl-edge" },
  { word: "language", grade: 4, definition: "the words people use to speak and write", example: "She is learning a new language.", syllables: "lan-guage" },
  { word: "library", grade: 4, definition: "a place where you can borrow books", example: "I returned my books to the library.", syllables: "li-brar-y" },
  { word: "measure", grade: 4, definition: "to find the size or amount of something", example: "Use a ruler to measure the length.", syllables: "meas-ure" },
  { word: "million", grade: 4, definition: "the number 1,000,000", example: "A million stars filled the night sky.", syllables: "mil-lion" },
  { word: "natural", grade: 4, definition: "found in nature; not made by people", example: "The park is full of natural beauty.", syllables: "nat-u-ral" },
  { word: "opinion", grade: 4, definition: "what you think or believe about something", example: "In my opinion, the book was great.", syllables: "o-pin-ion" },
  { word: "probably", grade: 4, definition: "most likely; almost certainly", example: "It will probably rain this afternoon.", syllables: "prob-a-bly" },
  { word: "separate", grade: 4, definition: "to set apart or keep away from each other", example: "Please separate the white clothes from the colors.", syllables: "sep-a-rate" },
  { word: "thought", grade: 4, definition: "an idea in your mind", example: "She had a thought about how to solve the puzzle.", syllables: "thought" },

  // ──────────────────────────────────────────────
  // GRADE 5
  // ──────────────────────────────────────────────
  { word: "absence", grade: 5, definition: "being away or not present", example: "His absence from class was noticed by the teacher.", syllables: "ab-sence" },
  { word: "accomplish", grade: 5, definition: "to finish or achieve something", example: "She worked hard to accomplish her goal.", syllables: "ac-com-plish" },
  { word: "accurate", grade: 5, definition: "correct and free from mistakes", example: "The map gave accurate directions to the park.", syllables: "ac-cu-rate" },
  { word: "adventure", grade: 5, definition: "an exciting or unusual experience", example: "Camping in the mountains was a great adventure.", syllables: "ad-ven-ture" },
  { word: "although", grade: 5, definition: "even though", example: "Although it was cold, we still went outside.", syllables: "al-though" },
  { word: "ancient", grade: 5, definition: "very, very old; from long ago", example: "The ancient ruins were thousands of years old.", syllables: "an-cient" },
  { word: "announce", grade: 5, definition: "to say something publicly", example: "The principal will announce the winner at lunch.", syllables: "an-nounce" },
  { word: "anxious", grade: 5, definition: "worried or nervous about something", example: "She felt anxious before her first day at school.", syllables: "anx-ious" },
  { word: "arrange", grade: 5, definition: "to put things in a neat order", example: "Please arrange the books by size on the shelf.", syllables: "ar-range" },
  { word: "athlete", grade: 5, definition: "a person who is trained in sports", example: "The athlete practiced every single day.", syllables: "ath-lete" },
  { word: "average", grade: 5, definition: "the usual or typical amount", example: "The average temperature in July is 85 degrees.", syllables: "av-er-age" },
  { word: "awkward", grade: 5, definition: "clumsy or uncomfortable", example: "There was an awkward silence after the joke.", syllables: "awk-ward" },
  { word: "balance", grade: 5, definition: "to keep steady without falling", example: "She tried to balance a book on her head.", syllables: "bal-ance" },
  { word: "bargain", grade: 5, definition: "something bought at a low price; a good deal", example: "The shoes were a real bargain at half price.", syllables: "bar-gain" },
  { word: "behavior", grade: 5, definition: "the way a person acts", example: "Good behavior is expected in the classroom.", syllables: "be-hav-ior" },
  { word: "benefit", grade: 5, definition: "something that helps or is good for you", example: "One benefit of reading is a bigger vocabulary.", syllables: "ben-e-fit" },
  { word: "boundary", grade: 5, definition: "a line that marks the edge of an area", example: "The fence marks the boundary of our yard.", syllables: "bound-a-ry" },
  { word: "brilliant", grade: 5, definition: "very smart or very bright", example: "The scientist had a brilliant idea.", syllables: "bril-liant" },
  { word: "business", grade: 5, definition: "a company or the work of buying and selling", example: "Her family runs a small business downtown.", syllables: "busi-ness" },
  { word: "campaign", grade: 5, definition: "an organized effort to reach a goal", example: "The class ran a campaign to recycle more.", syllables: "cam-paign" },
  { word: "capable", grade: 5, definition: "having the skill or power to do something", example: "She is capable of solving hard problems.", syllables: "ca-pa-ble" },
  { word: "capital", grade: 5, definition: "the city where a government is based", example: "Washington, D.C. is the capital of the United States.", syllables: "cap-i-tal" },
  { word: "captain", grade: 5, definition: "the leader of a team or ship", example: "The captain led the team onto the field.", syllables: "cap-tain" },
  { word: "celebrate", grade: 5, definition: "to do something special for a happy event", example: "We will celebrate her birthday with a party.", syllables: "cel-e-brate" },
  { word: "century", grade: 5, definition: "a period of one hundred years", example: "That building has stood for over a century.", syllables: "cen-tu-ry" },
  { word: "certain", grade: 5, definition: "sure about something; without doubt", example: "I am certain the answer is correct.", syllables: "cer-tain" },
  { word: "character", grade: 5, definition: "a person in a story, or the qualities that make you who you are", example: "The main character in the book is very brave.", syllables: "char-ac-ter" },
  { word: "community", grade: 5, definition: "a group of people living in the same area", example: "The community came together to clean the park.", syllables: "com-mu-ni-ty" },
  { word: "comparison", grade: 5, definition: "looking at how two things are alike or different", example: "The teacher asked for a comparison of the two stories.", syllables: "com-par-i-son" },
  { word: "concentrate", grade: 5, definition: "to focus your attention on something", example: "It is hard to concentrate with all this noise.", syllables: "con-cen-trate" },
  { word: "conclusion", grade: 5, definition: "the end or final decision", example: "The detective came to a surprising conclusion.", syllables: "con-clu-sion" },
  { word: "confusion", grade: 5, definition: "the state of being mixed up or unclear", example: "There was confusion about which room to go to.", syllables: "con-fu-sion" },
  { word: "consequence", grade: 5, definition: "the result of an action", example: "One consequence of not studying is a bad grade.", syllables: "con-se-quence" },
  { word: "continue", grade: 5, definition: "to keep going without stopping", example: "Please continue reading where you left off.", syllables: "con-tin-ue" },
  { word: "cooperation", grade: 5, definition: "working together to get something done", example: "The project required cooperation from the whole class.", syllables: "co-op-er-a-tion" },
  { word: "temperature", grade: 5, definition: "how hot or cold something is", example: "The temperature outside dropped below freezing.", syllables: "tem-per-a-ture" },
  { word: "environment", grade: 5, definition: "the natural world around us", example: "Planting trees helps the environment.", syllables: "en-vi-ron-ment" },
  { word: "especially", grade: 5, definition: "more than usual; particularly", example: "I love all fruits, especially strawberries.", syllables: "es-pe-cial-ly" },
  { word: "February", grade: 5, definition: "the second month of the year", example: "Valentine's Day is in February.", syllables: "Feb-ru-ar-y", pronunciationOverride: "February" },
  { word: "experience", grade: 5, definition: "something that happens to you; knowledge gained by doing", example: "Traveling is a wonderful experience.", syllables: "ex-pe-ri-ence" },

  // ──────────────────────────────────────────────
  // GRADE 6
  // (first 20 already seeded; these are the additions)
  // ──────────────────────────────────────────────
  { word: "accommodate", grade: 6, definition: "to provide space or make room for", example: "The hotel can accommodate up to 200 guests.", syllables: "ac-com-mo-date" },
  { word: "acknowledge", grade: 6, definition: "to accept or admit the truth of something", example: "She had to acknowledge her mistake.", syllables: "ac-knowl-edge" },
  { word: "apparently", grade: 6, definition: "as far as one can see or understand", example: "Apparently, the game was canceled due to rain.", syllables: "ap-par-ent-ly" },
  { word: "catastrophe", grade: 6, definition: "a sudden and terrible disaster", example: "The flood was a catastrophe for the town.", syllables: "ca-tas-tro-phe" },
  { word: "conscience", grade: 6, definition: "an inner feeling of right and wrong", example: "His conscience told him to return the lost wallet.", syllables: "con-science" },
  { word: "exaggerate", grade: 6, definition: "to make something seem bigger than it really is", example: "He tends to exaggerate how far he can throw.", syllables: "ex-ag-ger-ate" },
  { word: "guarantee", grade: 6, definition: "a firm promise that something will happen", example: "The store offers a money-back guarantee.", syllables: "guar-an-tee" },
  { word: "independent", grade: 6, definition: "able to do things on your own", example: "She is very independent and does her own laundry.", syllables: "in-de-pen-dent" },
  { word: "mischievous", grade: 6, definition: "playfully causing trouble", example: "The mischievous puppy chewed up the slippers.", syllables: "mis-chie-vous" },
  { word: "necessary", grade: 6, definition: "needed; something you must have or do", example: "Water is necessary for all living things.", syllables: "nec-es-sar-y" },
  { word: "occurrence", grade: 6, definition: "something that happens; an event", example: "Thunderstorms are a common occurrence in summer.", syllables: "oc-cur-rence" },
  { word: "persuade", grade: 6, definition: "to talk someone into doing or believing something", example: "She tried to persuade him to join the team.", syllables: "per-suade" },
  { word: "privilege", grade: 6, definition: "a special right or advantage", example: "It is a privilege to meet the author.", syllables: "priv-i-lege" },
  { word: "recommend", grade: 6, definition: "to suggest something as a good choice", example: "I recommend the pizza at that restaurant.", syllables: "rec-om-mend" },
  { word: "rhythm", grade: 6, definition: "a regular repeated pattern of sound or movement", example: "The drummer kept a steady rhythm.", syllables: "rhy-thm" },
  { word: "schedule", grade: 6, definition: "a plan that lists times for events or tasks", example: "Check the schedule to see when practice starts.", syllables: "sched-ule" },
  { word: "sufficient", grade: 6, definition: "enough; as much as is needed", example: "We have sufficient food for the whole trip.", syllables: "suf-fi-cient" },
  { word: "thorough", grade: 6, definition: "done carefully and completely", example: "She did a thorough job cleaning her room.", syllables: "thor-ough" },
  { word: "vegetable", grade: 6, definition: "a plant grown for food", example: "Broccoli is a healthy vegetable.", syllables: "veg-e-ta-ble" },
  { word: "abbreviate", grade: 6, definition: "to shorten a word or phrase", example: "You can abbreviate 'doctor' as 'Dr.'", syllables: "ab-bre-vi-ate" },
  { word: "abundant", grade: 6, definition: "existing in large amounts; plentiful", example: "Rain is abundant in the tropical forest.", syllables: "a-bun-dant" },
  { word: "acquaintance", grade: 6, definition: "a person you know slightly but not well", example: "He is an acquaintance from summer camp.", syllables: "ac-quain-tance" },
  { word: "adequate", grade: 6, definition: "good enough for a purpose", example: "Make sure you get adequate sleep before the test.", syllables: "ad-e-quate" },
  { word: "adolescent", grade: 6, definition: "a young person between childhood and adulthood", example: "The adolescent was excited to start middle school.", syllables: "ad-o-les-cent" },
  { word: "aggravate", grade: 6, definition: "to make something worse, or to annoy", example: "Scratching the bug bite will only aggravate it.", syllables: "ag-gra-vate" },
  { word: "allegiance", grade: 6, definition: "loyalty or commitment to a group or cause", example: "They pledged their allegiance to the flag.", syllables: "al-le-giance" },
  { word: "amateur", grade: 6, definition: "a person who does something for fun, not as a job", example: "She is an amateur photographer who loves sunsets.", syllables: "am-a-teur" },
  { word: "anonymous", grade: 6, definition: "by someone whose name is not known", example: "The generous donation was made by an anonymous person.", syllables: "a-non-y-mous" },
  { word: "anticipate", grade: 6, definition: "to expect something to happen", example: "We anticipate a big crowd at the concert.", syllables: "an-tic-i-pate" },
  { word: "appreciate", grade: 6, definition: "to be thankful for something or understand its value", example: "I appreciate your help with the project.", syllables: "ap-pre-ci-ate" },
  { word: "appropriate", grade: 6, definition: "right or suitable for a situation", example: "Wear appropriate shoes for the hike.", syllables: "ap-pro-pri-ate" },
  { word: "authorize", grade: 6, definition: "to give official permission", example: "Only the principal can authorize a field trip.", syllables: "au-thor-ize" },
  { word: "beneficial", grade: 6, definition: "helpful; producing good results", example: "Exercise is beneficial for your health.", syllables: "ben-e-fi-cial" },
  { word: "cemetery", grade: 6, definition: "a place where people are buried", example: "We visited the old cemetery on the hill.", syllables: "cem-e-ter-y" },
  { word: "circumstance", grade: 6, definition: "a condition or fact connected to an event", example: "Under the circumstance, we decided to stay home.", syllables: "cir-cum-stance" },
  { word: "colleague", grade: 6, definition: "a person you work with", example: "She invited a colleague to the meeting.", syllables: "col-league" },
  { word: "committee", grade: 6, definition: "a group of people chosen to do a task", example: "The committee planned the school dance.", syllables: "com-mit-tee" },
  { word: "communicate", grade: 6, definition: "to share information with others", example: "We use phones to communicate with friends.", syllables: "com-mu-ni-cate" },
  { word: "controversy", grade: 6, definition: "a public disagreement or argument", example: "The new rule caused controversy among the students.", syllables: "con-tro-ver-sy" },
  { word: "correspond", grade: 6, definition: "to match or be similar; to write letters", example: "The numbers on the key correspond to the rooms.", syllables: "cor-re-spond" },

  // ──────────────────────────────────────────────
  // GRADE 7
  // ──────────────────────────────────────────────
  { word: "absurd", grade: 7, definition: "completely silly or unreasonable", example: "The idea of flying pigs is absurd.", syllables: "ab-surd" },
  { word: "accessible", grade: 7, definition: "easy to reach, enter, or use", example: "The building is accessible to people in wheelchairs.", syllables: "ac-ces-si-ble" },
  { word: "accumulate", grade: 7, definition: "to gather or pile up over time", example: "Dust will accumulate if you do not clean.", syllables: "ac-cu-mu-late" },
  { word: "adjacent", grade: 7, definition: "next to or near something", example: "The park is adjacent to the school.", syllables: "ad-ja-cent" },
  { word: "ambiguous", grade: 7, definition: "having more than one possible meaning; unclear", example: "The instructions were ambiguous and hard to follow.", syllables: "am-big-u-ous" },
  { word: "apparently", grade: 7, definition: "as far as one can tell; seemingly", example: "He apparently forgot about the meeting.", syllables: "ap-par-ent-ly" },
  { word: "authentic", grade: 7, definition: "real and genuine, not fake", example: "The museum displayed authentic artifacts from Egypt.", syllables: "au-then-tic" },
  { word: "bibliography", grade: 7, definition: "a list of books or sources used in research", example: "She included a bibliography at the end of her report.", syllables: "bib-li-og-ra-phy" },
  { word: "camouflage", grade: 7, definition: "colors or patterns that help something blend in", example: "The lizard uses camouflage to hide from predators.", syllables: "cam-ou-flage" },
  { word: "catastrophic", grade: 7, definition: "causing sudden and great damage", example: "The earthquake had catastrophic effects on the city.", syllables: "cat-a-stroph-ic" },
  { word: "chronological", grade: 7, definition: "arranged in the order that things happened", example: "List the events in chronological order.", syllables: "chron-o-log-i-cal" },
  { word: "commemorate", grade: 7, definition: "to honor the memory of someone or something", example: "The statue was built to commemorate the founder.", syllables: "com-mem-o-rate" },
  { word: "compulsory", grade: 7, definition: "required; must be done", example: "Wearing a seatbelt is compulsory.", syllables: "com-pul-so-ry" },
  { word: "conceivable", grade: 7, definition: "possible to imagine or believe", example: "It is conceivable that it could snow in April.", syllables: "con-ceiv-a-ble" },
  { word: "consensus", grade: 7, definition: "a general agreement among a group", example: "The team reached a consensus on the plan.", syllables: "con-sen-sus" },
  { word: "contemporary", grade: 7, definition: "belonging to the present time; modern", example: "The gallery features contemporary art.", syllables: "con-tem-po-rar-y" },
  { word: "contradict", grade: 7, definition: "to say the opposite of what someone else said", example: "The witness seemed to contradict her earlier statement.", syllables: "con-tra-dict" },
  { word: "conventional", grade: 7, definition: "following the usual or traditional way", example: "He chose a conventional approach to the problem.", syllables: "con-ven-tion-al" },
  { word: "curriculum", grade: 7, definition: "the subjects and topics taught in a school", example: "Science is part of the school curriculum.", syllables: "cur-ric-u-lum" },
  { word: "demographic", grade: 7, definition: "relating to the study of populations", example: "The survey collected demographic information.", syllables: "dem-o-graph-ic" },
  { word: "deteriorate", grade: 7, definition: "to become worse over time", example: "The old house began to deteriorate.", syllables: "de-te-ri-o-rate" },
  { word: "dilemma", grade: 7, definition: "a situation where you must choose between two hard options", example: "She faced a dilemma about which school to attend.", syllables: "di-lem-ma" },
  { word: "distinguish", grade: 7, definition: "to tell the difference between two things", example: "Can you distinguish between the two shades of blue?", syllables: "dis-tin-guish" },
  { word: "elaborate", grade: 7, definition: "detailed and complex; to explain in more detail", example: "The chef prepared an elaborate meal for the guests.", syllables: "e-lab-o-rate" },
  { word: "equivalent", grade: 7, definition: "equal in value, amount, or meaning", example: "One meter is roughly equivalent to three feet.", syllables: "e-quiv-a-lent" },
  { word: "essential", grade: 7, definition: "absolutely necessary; extremely important", example: "Water is essential for survival.", syllables: "es-sen-tial" },
  { word: "exquisite", grade: 7, definition: "extremely beautiful or carefully made", example: "The jeweler crafted an exquisite necklace.", syllables: "ex-qui-site" },
  { word: "fascinate", grade: 7, definition: "to attract and hold someone's attention", example: "Dinosaurs fascinate many young scientists.", syllables: "fas-ci-nate" },
  { word: "harassment", grade: 7, definition: "behavior that annoys or threatens someone repeatedly", example: "The school has a strict policy against harassment.", syllables: "ha-rass-ment" },
  { word: "hypocrite", grade: 7, definition: "a person who pretends to believe something they do not", example: "He was called a hypocrite for breaking his own rules.", syllables: "hyp-o-crite" },
  { word: "influential", grade: 7, definition: "having a big effect on people or events", example: "She is one of the most influential leaders in history.", syllables: "in-flu-en-tial" },
  { word: "legitimate", grade: 7, definition: "allowed by law or rules; valid", example: "He had a legitimate reason for being late.", syllables: "le-git-i-mate" },
  { word: "maintenance", grade: 7, definition: "the work of keeping something in good condition", example: "Regular maintenance keeps the car running smoothly.", syllables: "main-te-nance" },
  { word: "miscellaneous", grade: 7, definition: "made up of many different kinds of things", example: "The drawer was full of miscellaneous items.", syllables: "mis-cel-la-ne-ous" },
  { word: "negotiate", grade: 7, definition: "to discuss something to reach an agreement", example: "The two sides will negotiate a fair deal.", syllables: "ne-go-ti-ate" },
  { word: "phenomenon", grade: 7, definition: "something unusual or remarkable that happens", example: "The northern lights are a natural phenomenon.", syllables: "phe-nom-e-non" },
  { word: "predominant", grade: 7, definition: "the most common, powerful, or noticeable", example: "Blue is the predominant color in the painting.", syllables: "pre-dom-i-nant" },
  { word: "questionnaire", grade: 7, definition: "a set of written questions used to gather information", example: "Please fill out this questionnaire about your habits.", syllables: "ques-tion-naire" },
  { word: "significant", grade: 7, definition: "important or large enough to have an effect", example: "There was a significant drop in temperature overnight.", syllables: "sig-nif-i-cant" },
  { word: "thorough", grade: 7, definition: "covering every detail; complete and careful", example: "The inspector did a thorough check of the building.", syllables: "thor-ough" },

  // ──────────────────────────────────────────────
  // GRADE 8
  // ──────────────────────────────────────────────
  { word: "accommodate", grade: 8, definition: "to fit in with someone's needs or requests", example: "The schedule was adjusted to accommodate everyone.", syllables: "ac-com-mo-date" },
  { word: "acquiesce", grade: 8, definition: "to accept something without protest", example: "After much debate, she decided to acquiesce.", syllables: "ac-qui-esce", pronunciationOverride: "ak-wee-ess" },
  { word: "aesthetic", grade: 8, definition: "relating to beauty or how things look", example: "The room had a simple but pleasing aesthetic.", syllables: "aes-thet-ic" },
  { word: "ambivalent", grade: 8, definition: "having mixed or conflicting feelings", example: "He felt ambivalent about moving to a new city.", syllables: "am-biv-a-lent" },
  { word: "anachronism", grade: 8, definition: "something placed in the wrong time period", example: "A knight using a cell phone would be an anachronism.", syllables: "a-nach-ro-nism" },
  { word: "belligerent", grade: 8, definition: "hostile and eager to fight", example: "The belligerent player was removed from the game.", syllables: "bel-lig-er-ent" },
  { word: "benevolent", grade: 8, definition: "kind and generous", example: "The benevolent neighbor brought meals to the family.", syllables: "be-nev-o-lent" },
  { word: "bureaucracy", grade: 8, definition: "a system with many complicated rules and processes", example: "The bureaucracy made it hard to get a simple permit.", syllables: "bu-reauc-ra-cy" },
  { word: "camaraderie", grade: 8, definition: "a feeling of friendship and trust in a group", example: "There was great camaraderie among the teammates.", syllables: "ca-ma-ra-der-ie", pronunciationOverride: "kah-muh-rah-duh-ree" },
  { word: "capitulate", grade: 8, definition: "to surrender or give in", example: "After a long siege, the castle was forced to capitulate.", syllables: "ca-pit-u-late" },
  { word: "conscientious", grade: 8, definition: "very careful and thorough about doing things right", example: "She is a conscientious student who always checks her work.", syllables: "con-sci-en-tious" },
  { word: "corroborate", grade: 8, definition: "to confirm or support with evidence", example: "The second witness was able to corroborate the story.", syllables: "cor-rob-o-rate" },
  { word: "curriculum", grade: 8, definition: "the set of courses and content offered by a school", example: "The new curriculum includes more science labs.", syllables: "cur-ric-u-lum" },
  { word: "decadent", grade: 8, definition: "having low morals, or luxuriously self-indulgent", example: "The decadent chocolate cake had three rich layers.", syllables: "dec-a-dent" },
  { word: "deference", grade: 8, definition: "polite respect and submission to someone", example: "The student spoke with deference to the judge.", syllables: "def-er-ence" },
  { word: "deprecate", grade: 8, definition: "to express disapproval of something", example: "He would often deprecate his own achievements.", syllables: "dep-re-cate" },
  { word: "discrepancy", grade: 8, definition: "a difference between things that should match", example: "There was a discrepancy between the two reports.", syllables: "dis-crep-an-cy" },
  { word: "disseminate", grade: 8, definition: "to spread information widely", example: "The internet helps disseminate news quickly.", syllables: "dis-sem-i-nate" },
  { word: "eccentricity", grade: 8, definition: "the quality of being unusual or strange", example: "His eccentricity made him a colorful character.", syllables: "ec-cen-tric-i-ty" },
  { word: "eloquent", grade: 8, definition: "able to speak or write clearly and powerfully", example: "The speaker gave an eloquent speech about justice.", syllables: "el-o-quent" },
  { word: "embellish", grade: 8, definition: "to decorate or add details, sometimes untrue ones", example: "He tends to embellish his fishing stories.", syllables: "em-bel-lish" },
  { word: "exacerbate", grade: 8, definition: "to make a bad situation even worse", example: "Yelling will only exacerbate the argument.", syllables: "ex-ac-er-bate" },
  { word: "formidable", grade: 8, definition: "inspiring fear or respect through strength or size", example: "The opposing team was a formidable challenge.", syllables: "for-mi-da-ble" },
  { word: "gregarious", grade: 8, definition: "very sociable and fond of company", example: "Her gregarious personality made her popular.", syllables: "gre-gar-i-ous" },
  { word: "idiosyncrasy", grade: 8, definition: "an unusual habit or way of behaving", example: "One of his idiosyncrasies is eating pizza with a fork.", syllables: "id-i-o-syn-cra-sy" },
  { word: "impeccable", grade: 8, definition: "flawless; without any mistakes", example: "Her impeccable manners impressed everyone.", syllables: "im-pec-ca-ble" },
  { word: "juxtapose", grade: 8, definition: "to place two things side by side for comparison", example: "The artist liked to juxtapose dark and light colors.", syllables: "jux-ta-pose" },
  { word: "labyrinth", grade: 8, definition: "a complicated maze or network of paths", example: "The garden had a labyrinth made of tall hedges.", syllables: "lab-y-rinth" },
  { word: "meticulous", grade: 8, definition: "extremely careful about details", example: "She kept meticulous notes in every class.", syllables: "me-tic-u-lous" },
  { word: "nonchalant", grade: 8, definition: "calm and relaxed, as if nothing matters", example: "He gave a nonchalant shrug when asked about the test.", syllables: "non-cha-lant", pronunciationOverride: "non-shuh-lahnt" },
  { word: "ostentatious", grade: 8, definition: "showy in a way meant to impress", example: "The ostentatious mansion had gold-plated faucets.", syllables: "os-ten-ta-tious" },
  { word: "paradox", grade: 8, definition: "a statement that seems to contradict itself but may be true", example: "It is a paradox that less can sometimes be more.", syllables: "par-a-dox" },
  { word: "perseverance", grade: 8, definition: "continuing to try despite difficulty", example: "Her perseverance paid off when she finally won.", syllables: "per-se-ver-ance" },
  { word: "prerogative", grade: 8, definition: "a right or privilege belonging to a particular person", example: "It is your prerogative to choose which team to join.", syllables: "pre-rog-a-tive" },
  { word: "reconnaissance", grade: 8, definition: "a survey or exploration to gather information", example: "The scouts did reconnaissance of the trail.", syllables: "re-con-nais-sance", pronunciationOverride: "ree-kah-nuh-suhns" },
  { word: "surreptitious", grade: 8, definition: "done secretly so that others do not notice", example: "He took a surreptitious glance at the answer key.", syllables: "sur-rep-ti-tious" },
  { word: "unanimous", grade: 8, definition: "agreed on by everyone", example: "The vote to cancel homework was unanimous.", syllables: "u-nan-i-mous" },
  { word: "versatile", grade: 8, definition: "able to do many different things well", example: "She is a versatile athlete who plays three sports.", syllables: "ver-sa-tile" },
  { word: "vengeance", grade: 8, definition: "punishment inflicted in return for a wrong", example: "The hero sought vengeance for the destruction of his village.", syllables: "ven-geance" },
  { word: "whimsical", grade: 8, definition: "playfully unusual or unpredictable", example: "The whimsical artwork featured dancing animals.", syllables: "whim-si-cal" },

  // ──────────────────────────────────────────────
  // GRADE 9
  // ──────────────────────────────────────────────
  { word: "acquiescence", grade: 9, definition: "the act of accepting something without protest", example: "Her acquiescence surprised everyone who expected a fight.", syllables: "ac-qui-es-cence", pronunciationOverride: "ak-wee-es-uhns" },
  { word: "amalgamate", grade: 9, definition: "to combine or unite into one", example: "The two companies plan to amalgamate next year.", syllables: "a-mal-ga-mate" },
  { word: "ameliorate", grade: 9, definition: "to make a bad situation better", example: "The new policy helped ameliorate the traffic problem.", syllables: "a-mel-io-rate" },
  { word: "antithesis", grade: 9, definition: "the exact opposite of something", example: "His messy room is the antithesis of organization.", syllables: "an-tith-e-sis" },
  { word: "bourgeois", grade: 9, definition: "relating to the middle class, often focused on material things", example: "The novel criticized bourgeois values.", syllables: "bour-geois", pronunciationOverride: "boor-zhwah" },
  { word: "circumlocution", grade: 9, definition: "using many words when fewer would do", example: "His circumlocution made it hard to understand his point.", syllables: "cir-cum-lo-cu-tion" },
  { word: "conflagration", grade: 9, definition: "a large, destructive fire", example: "The conflagration destroyed several city blocks.", syllables: "con-fla-gra-tion" },
  { word: "conglomerate", grade: 9, definition: "a large company made of many smaller businesses", example: "The media conglomerate owns newspapers and TV stations.", syllables: "con-glom-er-ate" },
  { word: "dichotomy", grade: 9, definition: "a division into two opposite groups or ideas", example: "There is a dichotomy between what he says and what he does.", syllables: "di-chot-o-my" },
  { word: "discernible", grade: 9, definition: "able to be seen, noticed, or understood", example: "There was no discernible difference between the two samples.", syllables: "dis-cern-i-ble" },
  { word: "disingenuous", grade: 9, definition: "not truly honest or sincere", example: "His apology felt disingenuous because he kept smiling.", syllables: "dis-in-gen-u-ous" },
  { word: "eclectic", grade: 9, definition: "made up of ideas or styles from a wide variety of sources", example: "Her music taste is eclectic, from jazz to hip-hop.", syllables: "ec-lec-tic" },
  { word: "effervescent", grade: 9, definition: "bubbly and enthusiastic, or fizzy", example: "Her effervescent personality lit up the room.", syllables: "ef-fer-ves-cent" },
  { word: "egregious", grade: 9, definition: "outstandingly bad; shockingly terrible", example: "The referee made an egregious error on the call.", syllables: "e-gre-gious" },
  { word: "ephemeral", grade: 9, definition: "lasting for a very short time", example: "The beauty of cherry blossoms is ephemeral.", syllables: "e-phem-er-al" },
  { word: "equivocal", grade: 9, definition: "open to more than one interpretation; unclear on purpose", example: "The politician gave an equivocal answer to the question.", syllables: "e-quiv-o-cal" },
  { word: "fastidious", grade: 9, definition: "very attentive to detail and accuracy", example: "The fastidious chef measured every ingredient precisely.", syllables: "fas-tid-i-ous" },
  { word: "gratuitous", grade: 9, definition: "given without good reason; uncalled for", example: "The movie had gratuitous special effects that added nothing.", syllables: "gra-tu-i-tous" },
  { word: "hegemony", grade: 9, definition: "leadership or dominance of one group over others", example: "The empire maintained hegemony over the region for centuries.", syllables: "he-gem-o-ny", pronunciationOverride: "heh-jem-uh-nee" },
  { word: "idiosyncratic", grade: 9, definition: "peculiar to one person; uniquely individual", example: "His idiosyncratic teaching style kept students engaged.", syllables: "id-i-o-syn-crat-ic" },
  { word: "impervious", grade: 9, definition: "unable to be affected or penetrated", example: "The raincoat was impervious to water.", syllables: "im-per-vi-ous" },
  { word: "incongruous", grade: 9, definition: "not in harmony; out of place", example: "A snowman in the desert would look incongruous.", syllables: "in-con-gru-ous" },
  { word: "inexorable", grade: 9, definition: "impossible to stop or prevent", example: "The inexorable march of time changes everything.", syllables: "in-ex-o-ra-ble" },
  { word: "magnanimous", grade: 9, definition: "generous and forgiving, especially to a rival", example: "The magnanimous winner congratulated the other team.", syllables: "mag-nan-i-mous" },
  { word: "metamorphosis", grade: 9, definition: "a major change in form or character", example: "A caterpillar undergoes metamorphosis to become a butterfly.", syllables: "met-a-mor-pho-sis" },
  { word: "obsequious", grade: 9, definition: "too eager to serve or please someone", example: "The obsequious waiter hovered over the table.", syllables: "ob-se-qui-ous" },
  { word: "ostentatious", grade: 9, definition: "designed to attract attention and impress", example: "The billionaire lived in an ostentatious mansion.", syllables: "os-ten-ta-tious" },
  { word: "paradigm", grade: 9, definition: "a typical example or model of something", example: "The discovery created a new paradigm in science.", syllables: "par-a-digm", pronunciationOverride: "pair-uh-dime" },
  { word: "perfunctory", grade: 9, definition: "done without care or interest; routine", example: "He gave a perfunctory nod without looking up.", syllables: "per-func-to-ry" },
  { word: "prestidigitation", grade: 9, definition: "magic tricks performed with the hands; sleight of hand", example: "The magician's prestidigitation amazed the audience.", syllables: "pres-ti-dig-i-ta-tion" },
  { word: "quintessential", grade: 9, definition: "representing the most perfect example of something", example: "Apple pie is the quintessential American dessert.", syllables: "quin-tes-sen-tial" },
  { word: "recalcitrant", grade: 9, definition: "stubbornly refusing to obey or cooperate", example: "The recalcitrant student refused to sit down.", syllables: "re-cal-ci-trant" },
  { word: "surreptitious", grade: 9, definition: "kept secret because it would not be approved of", example: "She made a surreptitious phone call during class.", syllables: "sur-rep-ti-tious" },
  { word: "sycophant", grade: 9, definition: "a person who flatters someone important to gain advantage", example: "The king was surrounded by sycophants who agreed with everything.", syllables: "syc-o-phant" },
  { word: "ubiquitous", grade: 9, definition: "seeming to be everywhere at once", example: "Smartphones have become ubiquitous in modern life.", syllables: "u-biq-ui-tous" },
  { word: "unequivocal", grade: 9, definition: "leaving no doubt; completely clear", example: "The answer was an unequivocal yes.", syllables: "un-e-quiv-o-cal" },
  { word: "vicissitude", grade: 9, definition: "an unexpected change in fortune or circumstances", example: "Life is full of vicissitudes that test our strength.", syllables: "vi-cis-si-tude" },
  { word: "vociferous", grade: 9, definition: "loud and forceful in expressing feelings", example: "The crowd gave vociferous support to the home team.", syllables: "vo-cif-er-ous" },
  { word: "xenophobia", grade: 9, definition: "fear or hatred of people from other countries", example: "Education can help reduce xenophobia.", syllables: "xen-o-pho-bi-a", pronunciationOverride: "zen-uh-foh-bee-uh" },
  { word: "zealous", grade: 9, definition: "showing great energy and enthusiasm for a cause", example: "The zealous volunteers worked through the night.", syllables: "zeal-ous" },
];
